Compelover/Compelover.WEBUI/Areas/Member/ViewModels/PasswordChangeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Compelover.WEBUI.Areas.Member.ViewModels
{
    public class PasswordChangeViewModel
    {
        [Required(ErrorMessage = "Eski Şifreniz Gereklidir.")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Şifre 4 karekterli olmalı")]
        public string PasswordOld { get; set; }

        [Required(ErrorMessage = "Yeni Şifreniz Gereklidir.")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Şifre 4 karekterli olmalı")]
        public string PasswordNew { get; set; }

        [Required(ErrorMessage = "Tekrar Yeni Şifreniz Gereklidir.")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Şifre 4 karekterli olmalı")]
        [Compare("PasswordNew",ErrorMessage = "Yeni Şifre ve Onay Şifre birbirinden farklı.")]
        public string PasswordConfirm { get; set; }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/Controllers/BlogController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using AutoMapper;
using Compelover.Business.Notional;
using Compelover.Entities.DTOs;
using Compelover.Entities.Tangible;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Compelover.WEBUI.Areas.Member.Controllers
{
    [Authorize]
    [Area("Member")]
    public class BlogController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IBlogService _blogService;
        private readonly UserManager<AppUser> _userManager;

        public BlogController(IMapper mapper, IBlogService blogService, UserManager<AppUser> userManager)
        {
            _mapper = mapper;
            _blogService = blogService;
            _userManager = userManager;
        }

        public IActionResult BlogList()
        {
            var listBlog = _blogService.ListOfBlog();
            return View(listBlog);
        }

        public IActionResult BlogPostAdd(Blog blog)
        {
            var addedBlogPost = _mapper.Map<BlogDto>(blog);
            return View(addedBlogPost);
        }

        [HttpPost]
        public async Task<IActionResult> BlogPostAdd(BlogDto blogDto, IFormFile blogPicture)
        {
            var blogPost = new Blog();
            if (blogPicture != null && blogPicture.Length > 0)
            {
                var fileName = Guid.NewGuid() + Path.GetExtension(blogPicture.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/BlogPicture", fileName);
                //resmi kaydetme.
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await blogPicture.CopyToAsync(stream);
                    blogPost.ImageBlog = "/BlogPicture/" + fileName;
                }
            }

            blogPost.Title = blogDto.Title;
            blogPost.ShortDescription = blogDto.ShortDescription;
            blogPost.Description = blogDto.Description;
            blogPost.AppUserId = blogDto.AppUserId;
            blogPost.PostedTime = blogDto.PostedTime;
            // blogPost.AppUser = blogDto.AppUser;
            _blogService.AddBlogPost(blogPost);
            return RedirectToAction("BlogList");
        }

        public IActionResult BlogContinuation(string blogId)
        {
            var blogDetail = _mapper.Map<BlogDto>(_blogService.GetByBlogId(blogId));
            return View(blogDetail);
        }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Compelover.Business.Notional;
using Compelover.Entities.DTOs;
using Compelover.Entities.Tangible;
using Compelover.WEBUI.Areas.Member.ViewModels;
using Compelover.WEBUI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Compelover.WEBUI.Areas.Member.Controllers
{
    [Authorize]
    [Area("Member")]
    public class MemberController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IMapper _mapper;
        private readonly IBlogService _blogService;
        private readonly IUserService _userService;

        public MemberController(UserManager<AppUser> userManager, IMapper mapper, SignInManager<AppUser> signInManager,
            IBlogService blogService, IUserService userService)
        {
            _userManager = userManager;
            _mapper = mapper;
            _signInManager = signInManager;
            _blogService = blogService;
            _userService = userService;
        }

        private async Task<UserViewModel> FinByNameUser()
        {
            var findByUserMap = _mapper.Map<UserViewModel>(await _userManager.FindByNameAsync(User.Identity.Name));
            return findByUserMap;
        }


        public async Task<IActionResult> Index()
        {
            var listOfIndex = await FinByNameUser();
            return View(listOfIndex);
        }
        [HttpPost]
        public async Task<IActionResult> UserEdit(UserViewModel userViewModel, IFormFile userPicture)
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (userPicture != null && userPicture.Length > 0)
            {
                var fileName = Guid.NewGuid() + Path.GetExtension(userPicture.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/UserPicture", fileName);
                //resmi kaydetme.
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await userPicture.CopyToAsync(stream);
                    user.Picture = "/UserPicture/" + fileName;
                }
            }

            user.UserName = userViewModel.UserName;
            user.Email = userViewModel.Email;
            user.PhoneNumber = userViewModel.PhoneNumber;
            user.City = userViewModel.City;
            user.BirthDay = userViewModel.BirthDay;
            user.Gender = userViewModel.Gender;
            IdentityResult result = await _userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                //Cooki'yi güncellemek için.
                await _userManager.UpdateSecurityStampAsync(user);
                await _signInManager.SignOutAsync();
                await _signInManager.SignInAsync(user, true);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var itemError in result.Errors)
                {
                    ModelState.AddModelError("", itemError.Description);
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult PasswordChange()
        {
            ViewBag.Member = typeof(UserViewModel);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel passwordChange)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name); //Kullanıcıya ulaştık.
                bool exist =
                    await _userManager.CheckPasswordAsync(user,
                        passwordChange.PasswordOld); //eski şifresi doğru mu?çek etmek.
                if (exist) //kullanıcı eski şifreyi doğru girmiş ise(true)
                {
                    IdentityResult result = await _userManager.ChangePasswordAsync(user, passwordChange.PasswordOld,
                        passwordChange.PasswordNew); //şifreyi değiştirdik.
                    if (result.Succeeded)
                    {
                        await _userManager
                            .UpdateSecurityStampAsync(
                                user); //bunu yazmazsak kullanıcı eski şifre ile dolaşmaya devam eder.
                        //Kullanıcıya biz tekrardan çıkış ve giriş işlemi yaptırdık kullanıcı bunu anlayamacak ve cooki'si tekrar oluşacak.
                        await _signInManager.SignOutAsync();
                        //yeni şifre ile yeniden giriş yaptırdık.
                        await _signInManager.PasswordSignInAsync(user, passwordChange.PasswordNew, true, false);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Eski Şifre Hatalı.");
                }
            }

            return View(passwordChange);
        }

        public IActionResult UserProfile(string userId)
        {
            var userArea = _mapper.Map<UserListDto>(_userService.GetByUserId(userId));
            return View(userArea);
            // var userArea = _userManager.FindByNameAsync(User.Identity.Name).Result;
            // return View(userArea);
        }

        public IActionResult BlogUser(string userId)
        {
            var blogUser = _mapper.Map<List<BlogDto>>(_blogService.GetUserBlogCount(userId));
            return View(blogUser);
            // var blogUser = _blogService.GetUserBlogCount(userId);
            // return View(blogUser);
        }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/Controllers/UserController.cs
using AutoMapper;
using Compelover.Business.Notional;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Compelover.WEBUI.Areas.Member.Controllers
{
    [Authorize]
    [Area("Member")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public UserController(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        public IActionResult UserList(string searchedUser = null)
        {
            if (!string.IsNullOrEmpty(searchedUser))
            {
                var findUser = _userService.SearchUser(searchedUser);
                return View(findUser);
            }

            var listPeople = _userService.ListOfUsers();
            return View(listPeople);
        }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/ViewComponents/DropdownViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Compelover.WEBUI.Areas.Member.ViewComponents
{
    public class DropdownViewComponent : ViewComponent
    {
        public ViewViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/ViewComponents/ListOfAllBlogPostViewComponent.cs
using Compelover.Business.Notional;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Compelover.WEBUI.Areas.Member.ViewComponents
{
    public class ListOfAllBlogPostViewComponent : ViewComponent
    {
        private readonly IBlogService _blogService;

        public ListOfAllBlogPostViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public ViewViewComponentResult Invoke()
        {
            var listOfAllBlog = _blogService.ListOfBlog();
            return View(listOfAllBlog);
        }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/ViewComponents/UserListViewComponent.cs
using System.Collections.Generic;
using AutoMapper;
using Compelover.Business.Notional;
using Compelover.WEBUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Compelover.WEBUI.Areas.Member.ViewComponents
{
    public class UserListViewComponent:ViewComponent
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;
        public UserListViewComponent(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        public ViewViewComponentResult Invoke()
        {
            var peopleList = _mapper.Map<List<UserViewModel>>(_userService.ForComponentUsersList());
            return View(peopleList);
        }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/ViewComponents/UserWrittenBlogsViewComponent.cs
using System.Collections.Generic;
using AutoMapper;
using Compelover.Business.Notional;
using Compelover.Entities.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Compelover.WEBUI.Areas.Member.ViewComponents
{
    public class UserWrittenBlogsViewComponent:ViewComponent
    {
        private readonly IMapper _mapper;
        private readonly IBlogService _blogService;
        public UserWrittenBlogsViewComponent(IMapper mapper, IBlogService blogService)
        {
            _mapper = mapper;
            _blogService = blogService;
        }

        public ViewViewComponentResult Invoke(string userId)
        {
            var blogUser = _mapper.Map<List<BlogDto>>(_blogService.GetUserBlogCount(userId));
            return View(blogUser);
        }
    }
}

Compelover/Compelover.WEBUI/Areas/Member/Views/Member/BlogUser.cshtml
@model System.Collections.Generic.List<Compelover.Entities.DTOs.BlogDto>
@{
    Layout = "_MemberLayout";
}
<div class="container">
    @foreach (var userName in Model)
    {
        <h1 style="font-family: 'Libre Baskerville', serif;" class="text-white text-center mb-3 mt-4">@userName.AppUserId 'ın Yazmış olduğu yazılar</h1>
        break;
    }
    <hr class="bg-pink mt-5">
    <div class="card-columns">
        @foreach (var listblog in Model)
        {
            <div class="card border-0">
                <img src="@listblog.ImageBlog" class="card-img-top" alt="">
                <a asp-route-userId="@listblog.AppUserId" asp-controller="Member" asp-action="BlogUser">
                    <small class="bg-secondary float-left text-white mt-4" style="font-size: 0.69rem;">@listblog.AppUserId</small>
                </a>
                <small class="bg-turquoise float-right text-white mt-4" style="font-size: 0.69rem;">@listblog.PostedTime.ToLongDateString()</small>
                <small class="float-right" style="margin-right: -17%;">
                    <a class="twitter-share-button mr-1" title="Twitter'da Paylaş" data-lang="tr" data-via="www.compelover.com" href="https://twitter.com/intent/tweet?text=@listblog.Title by @@@listblog.AppUserId www.compelover.com" _fcksavedurl="https://twitter.com/intent/tweet?text=Paylas" data-size="large">
                        <i class="fab fa-twitter text-info text-white"></i>
                    </a>
                    <a class="facebook-share-button" title="Facebook'ta Paylaş" href="http://www.facebook.com/sharer/sharer.php?s=100&p[url]=&p[images][0]=&p[title]=&p[summary]=" onclick_fckprotectedatt="%20onclick%3D%22%0A%0A%20%20%20%20window.open(%0A%0A%20%20%20%20%20%20'https%3A%2F%2Fwww.facebook.com%2Fsharer%2Fsharer.php%3Fu%3D'%2BencodeURIComponent(location.href)%2C%20%0A%0A%20%20%20%20%20%20'facebook-share-dialog'%2C%20%0A%0A%20%20%20%20%20%20'width%3D626%2Cheight%3D436')%3B%20%0A%0A%20%20%20%20return%20false%3B%22">
                        <i class="fab fa-facebook-f text-info"></i>
                    </a>
                </small>
                <div class="card-body mr-5 bg-dark text-white text-center">
                    <h5 style="font-family: 'Bebas Neue', cursive;">
                        @listblog.Title
                    </h5>
                    <p style="font-family: 'Pathway Gothic One', sans-serif;">@listblog.ShortDescription</p>
                    @if (@listblog.Description.Length > 2000)
                    {
                        <small style="font-family: 'Roboto', sans-serif;">Yazını'nın Tamamını Okumak için İnceleye <small class="bg-pink">Tıklayınız.</small></small>
                    }
                    else
                    {
                        <small>@listblog.Description</small>
                    }
                    <a asp-route-BlogId="@listblog.BlogId" asp-controller="Blog" asp-action="BlogContinuation" class="btn btn-outline-secondary text-white btn-block" style="font-family: 'Oswald', sans-serif;">Tamamı</a>
                </div>
            </div>
        }
    </div>
</div>

Compelover/Compelover.WEBUI/Areas/Member/Views/Member/Index.cshtml
@model Compelover.WEBUI.ViewModels.UserViewModel
@{
    Layout = "_MemberLayout";
}

@await Component.InvokeAsync("Dropdown")

<form method="post" asp-controller="User" asp-action="UserList">

    <section id="memberPage" class="py-5 bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="items text-center text-white">
                        <small class="text-white" style="letter-spacing: 2px;">HOŞ GELDİN</small>
                        <br>
                        <span style="font-family: 'Anton', sans-serif;font-size: 2.60rem; letter-spacing: 2px;">
                            <a asp-route-userId="@Model.Id" asp-controller="Member" asp-action="UserProfile" style="text-decoration: none;color: #fefefe;">
                                @Model.Name.ToUpper() @Model.SurName.ToUpper()
                            </a>
                        </span>
                        <br>
                    </div>
                    <div class="buttons text-center mt-2">
                        <a class="btn btn-outline-light btn-sm" style="font-family: 'Abril Fatface', cursive;border-radius: 10px;" title="Blog Post'u Yaz" asp-controller="Blog" asp-action="BlogPostAdd">
                            <i class="fab fa-steam-symbol fa-2x mr-2"></i>Bloğ'unu paylaş
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="description" class="py-5 text-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="prg-text text-white">
                        <span style="font-family: 'Yanone Kaffeesatz', sans-serif;font-size: 2.28rem;">
                            İnsanları keşfedip, & <span class="bg-turquoise text-white">yazılarını</span> okuyabilirsiniz!
                        </span>
                    </div>

                </div>

                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" id="searchedUser" name="searchedUser" class="search-input-value text-center mr-1" placeholder="Kullanıcı Ara">
                        <div class="search-button">
                            <i class="fas fa-search">
                                <input type="submit" value="Ara" class="search-value btn-sm">
                            </i>
                        </div>
                    </div>
                    <hr>
                    @await Component.InvokeAsync("UserList")

                </div>
            </div>
        </div>
    </section>
    <section id="areaThree" class="mt-4" style="background-color: #4e555b">
        <div class="list-blog-page mt-4">
            @await Component.InvokeAsync("ListOfAllBlogPost")

        </div>
    </section>
</form>

Compelover/Compelover.WEBUI/Areas/Member/Views/Member/PasswordChange.cshtml
@model Compelover.WEBUI.Areas.Member.ViewModels.PasswordChangeViewModel

@{
    Layout = "_MemberLayout";
}

<section id="passwordChange" class="py-5" style="background-color: #258c7f;">
    <div class="password-change-top text-center">
        <h4 class="text-white">Şifre Değiştirme</h4>
        <hr class="border-warning">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                <form method="post" asp-controller="Member" asp-action="PasswordChange">
                    <div class="form-group">
                        <i class="fas fa-anchor mr-2 fa-2x text-white"></i> <input type="password" asp-for="@Model.PasswordOld" class="password-reset-input" placeholder="Eski Şifreniz">
                        <span asp-validation-for="PasswordOld" class="badge badge-danger mt-2"></span>
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="password" asp-for="@Model.PasswordNew" class="password-reset-input text-warning" placeholder="Yeni Şifreniz"><i class="fab fa-affiliatetheme ml-2 fa-2x text-white"></i>
                        <span asp-validation-for="PasswordNew" class="badge badge-danger"></span>
                    </div>
                    <br>
                    <div class="form-group">
                        <i class="fab fa-500px mr-2 text-white fa-2x"></i> <input type="password" asp-for="@Model.PasswordConfirm" id="newPassword" class="password-reset-input" placeholder="Yeni Şifre Tekrarı">
                        <span asp-validation-for="PasswordConfirm" class="badge badge-danger mt-2"></span>
                    </div>
                    <br>
                    <div class="change-password-button text-center">
                        <input type="submit" class="btn btn-outline-warning btn-block" value="Şifre'yi Değiştir" style="border-radius: 50px;">
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

Compelover/Compelover.WEBUI/Areas/Member/Views/Member/UserProfile.cshtml
@using Compelover.Entities.DTOs
@model UserListDto
@{
    Layout = "_MemberLayout";
}
<section id="myprofile-area" class="py-5" style="background-color: #fefefe;">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="top-value">
                    <h4 class="text-dark font-weight-bold" style="font-family: 'Oswald', sans-serif;">
                        @Model.Name @Model.SurName
                    </h4>
                    <i class="fas fa-at text-dark mr-2"></i>
                    <small class="text-dark mr-2">@Model.UserName</small>
                    <br>
                    @if (Model.City == null)
                    {
                        <i class="fas fa-times mr-3 text-danger"></i>
                        <span style="font-family: 'IM Fell Double Pica',serif;font-size: small;">Şehir Belirtilmemiş.</span>
                    }
                    else
                    {
                        <i class="fas fa-map-marked-alt mr-2 text-danger"></i>
                        <span style="font-family: 'IM Fell Double Pica', serif;">@Model.City</span>
                    }
                    <br>
                    @if (Model.Gender == null)
                    {
                        <i class="fas fa-times mr-3 text-danger"></i>
                        <span style="font-family: 'IM Fell Double Pica',serif;font-size: small;">Cinsiyet Belirtilmemiş.</span>
                    }

                    else
                    {
                        <i class="fas fa-venus-mars mr-2 text-warning"></i>
                        <span style="font-family: 'IM Fell Double Pica', serif;">@Model.Gender</span>
                    }
                    <br>
                    @if (Model.BirthDay == null)
                    {
                        <i class="fas fa-times mr-3 text-danger"></i>
                        <span style="font-family: 'IM Fell Double Pica',serif;font-size:small;">Doğum Tarihi Belirtilmemiş.</span>
                    }
                    else
                    {
                        <i class="fas fa-birthday-cake mr-2 text-dark"></i>
                        <span style="font-family: 'IM Fell Double Pica',serif;">@Model.BirthDay?.ToLongDateString()</span>
                    }
                    <br>

                    <i class="fas fa-hourglass-start mr-3 mt-1 text-info"></i>
                    <span style="font-family: 'IM Fell Double Pica', serif;">@Model.SystemRegistrationDate.Value.ToLongDateString()</span>

                </div>
            </div>
            <div class="col-md-4">
                @if (Model.Picture == null)
                {
                    <img src="UserPicture/notPhoto.jpg" alt="" title="Fotoğraf Yükleyiniz." class="mb-1" style="border-radius: 50%;" width="128" height="128">
                }
                else
                {
                    <img src="@Model.Picture" alt="" title="@Model.UserName Kullanıcısı'nın Fotoğrafını Büyüt." class="mb-1" data-toggle="modal" data-target=".img-area-large" style="border-radius: 50%;" width="128" height="128">
                }
                <br>
                @if (User.Identity.Name == Model.UserName)
                {
                    <a class="profile-edit btn-sm" data-toggle="modal" data-target=".bd-example-modal-lg">Profili Düzenle</a>
                }
                else
                {
                    <a class="profile-edit btn-sm">Takip Et</a>
                }
            </div>

        </div>
        <hr class="border-white">
    </div>
</section>
<section id="listOfMyBlog" class="py-5">
    @* @foreach (var blog in Model) *@
    @* { *@
    @*     <h2>@blog.BlogId</h2> *@
    @* } *@
</section>

@*PROFİLİ DÜZENLE*@

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <section id="userId" class="py-5">
                <div class="user-edit-top text-center">
                    <h4 class="text-dark">Profil Düzenle</h4>
                    <hr class="border-danger">
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="jumbotron" style="border-radius: 30px;">
                                <div class="jumbotron-body shadow">
                                    <div class="user-edit-form text-center">

                                        <form method="post" asp-area="Member" asp-action="UserEdit" enctype="multipart/form-data">
                                            <div class="form-group">
                                                <i class="far fa-user mr-2 text-danger fa-2x"></i> <input type="text" asp-for="@Model.UserName" class="user-edit-input text-center">
                                            </div>
                                            <br>
                                            <div class="form-group">
                                                <input type="email" asp-for="@Model.Email" class="user-edit-input text-center"><i class="far fa-envelope-open ml-2 fa-2x text-danger"></i>
                                            </div>
                                            <br>
                                            <div class="form-group">
                                                <i class="fas fa-user-circle mr-2 text-danger fa-2x"></i>
                                                <input type="file" class="user-edit-input text-center" name="userPicture">
                                            </div>
                                            <br>
                                            <div class="form-group">
                                                <input type="tel" asp-for="@Model.PhoneNumber" class="user-edit-input text-center"><i class="fas fa-mobile text-danger ml-2 fa-2x"></i>
                                            </div>
                                            <br>
                                            <div class="form-group">
                                                <i class="fas fa-map-pin mr-2 fa-2x text-danger"></i> <input type="text" asp-for="@Model.City" class="user-edit-input text-center">
                                            </div>
                                            <br>
                                            <div class="form-group">
                                                <input type="date" asp-for="@Model.BirthDay" class="user-edit-input text-center"><i class="fas fa-birthday-cake ml-2 fa-2x text-danger"></i>
                                            </div>
                                            <br>
                                            <div class="form-group">
                                                <i class="fas fa-venus-mars mr-2 fa-2x text-danger"></i> <input type="text" asp-for="@Model.Gender" class="user-edit-input text-center">
                                            </div>
                                            <br>
                                            <div class="change-user-button">
                                                <input type="submit" class="btn btn-outline-secondary btn-block update-user-button" value="Bilgilerini Kaydet">
                                                <a asp-controller="Member" asp-action="PasswordChange" class="btn btn-outline-secondary btn-block update-user-button mt-2">Şifreni Değiştir</a>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

@*PROFİLİ DÜZENLE*@
@*----------------------------------------*@
@*FOTOĞRAF BÜYÜTMEK İÇİN*@
<div class="modal fade img-area-large" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">

        <div class="modal-content">
            <div class="content text-center">
                <img src="@Model.Picture" class="img-fluid text-center" width="450" height="450" alt="">

            </div>
        </div>

    </div>
</div>
@*FOTOĞRAF BÜYÜTMEK İÇİN*@